Update application_en.properties

diff --git a/.github/workflows/validate_encoding.yml b/.github/workflows/validate_encoding.yml
--- a/.github/workflows/validate_encoding.yml
+++ b/.github/workflows/validate_encoding.yml
@@ -1,15 +1,12 @@
-name: CI
-
-on: [pull_request]
+name: Validate-Encoding
+on: 
+  pull_request:
 
 jobs:
   build:
     runs-on: ubuntu-latest
-    
     steps:
       - name : checkoutcode
         uses: actions/checkout@v3
-      - name : validaciones
-        run: ls -la
-      - name: list the directory
-        run: for i in $(git show --pretty="format:" --name-only);do if [[ -e $i ]] && [[ 'file -b --mime-encoding $i' !=  us-ascii ]]; then echo "es archivo sin utf-8"; fi;done;
+      - name: Validate Encoding in Files
+        run: for i in $(git show --pretty="format:" --name-only);do if [[ -e $i &&  $(file -b --mime-encoding $i) !=  us-ascii ]]; then echo "$i es archivo sin utf-8" &&  bash -eo pipefail {0}; fi;done;
